-- Dados de demonstração (is_demo = 1): lotes publicados para o marketplace não começar vazio.
-- Remover depois do lançamento: DELETE FROM questions WHERE lot_id IN (SELECT id FROM lots WHERE is_demo = 1); DELETE FROM lots WHERE is_demo = 1;
INSERT OR IGNORE INTO users (id, name, email, role, seller_status) VALUES
  ('demo-vendedor', 'Vendedores de demonstração', 'demo-vendedor@gadon.com.br', 'vendedor', 'aprovado'),
  ('demo-comprador', 'Comprador de demonstração', 'demo-comprador@gadon.com.br', 'comprador', 'nao_iniciado');

INSERT INTO lots (seller_id, status, name, category, breed, sex, heads, weight_arroba, age_label, age_months, purpose, price_per_head, farm_name, owner_first_name, city, state, lat, lng, feeding, vaccination, traceability, gta_status, description, photos, is_demo, published_at) VALUES
  ('demo-vendedor', 'publicado', 'Nelore selecionado', 'Nelore', 'Nelore', 'Machos', 80, 12, '18 a 24 meses', 21, 'Engorda', 2330, 'Fazenda Santa Rita', 'Carlos', 'Campo Verde', 'MT', -15.55, -55.16, 'Pasto + suplementação mineral', 'Em dia (aftosa e clostridiose)', 'Identificação da fazenda', 'A emitir após a negociação', 'Machos Nelore uniformes, criados a pasto com suplementação mineral e manejo sanitário em dia. Lote pronto para a fase de engorda.', '["/home-hero-nelore.png","/nelore-cadastro.png"]', 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days')),
  ('demo-vendedor', 'publicado', 'Angus premium', 'Angus', 'Angus', 'Fêmeas', 50, 10, '20 a 28 meses', 24, 'Reprodução', 2350, 'Fazenda Boa Vista', 'Marta', 'Dourados', 'MS', -22.22, -54.81, 'Pasto rotacionado', 'Em dia (aftosa e brucelose)', 'SISBOV', 'A emitir após a negociação', 'Fêmeas Angus de linhagem selecionada, com bom desenvolvimento e aptidão para reprodução. Manejo em pasto rotacionado.', '["https://images.unsplash.com/photo-1662486750674-5cba308b8dab?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1698077754289-8d86b7e76ceb?auto=format&fit=crop&w=1200&q=85"]', 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days')),
  ('demo-vendedor', 'publicado', 'Nelore matriz', 'Nelore', 'Nelore', 'Fêmeas', 120, 15, '24 a 36 meses', 30, 'Reprodução', 2280, 'Fazenda JP', 'Renato', 'Aparecida do Taboado', 'MS', -20.09, -51.09, 'Pasto + sal proteinado na seca', 'Em dia (aftosa e brucelose)', 'Identificação da fazenda', 'A emitir após a negociação', 'Matrizes Nelore em idade reprodutiva, com histórico de manejo e boa condição corporal. Indicadas para formação ou reposição de plantel.', '["https://images.unsplash.com/photo-1555070319-a51174cb9529?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1554839465-be8f7c6786b5?auto=format&fit=crop&w=1200&q=85"]', 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days')),
  ('demo-vendedor', 'publicado', 'Cruza industrial', 'Cruza', 'Cruza industrial (Nelore × Angus)', 'Machos', 60, 10, '16 a 22 meses', 19, 'Engorda', 1980, 'Fazenda São Miguel', 'Antônio', 'Goiânia', 'GO', -16.68, -49.25, 'Pasto + ração de crescimento', 'Em dia (aftosa e clostridiose)', 'Identificação da fazenda', 'A emitir após a negociação', 'Machos cruza industrial com bom ganho de peso, indicados para engorda a pasto ou em confinamento.', '["https://images.unsplash.com/photo-1593175216843-9f1be1c3e468?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1593175217181-eddfe4c48e10?auto=format&fit=crop&w=1200&q=85"]', 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  ('demo-vendedor', 'publicado', 'Bezerros Nelore', 'Bezerros', 'Nelore', 'Machos', 40, 8, '8 a 12 meses', 10, 'Recria', 2750, 'Fazenda Horizonte', 'Luciana', 'Rondonópolis', 'MT', -16.47, -54.64, 'Creep feeding até a desmama', 'Protocolo de desmama completo', 'Identificação individual', 'A emitir após a negociação', 'Bezerros Nelore desmamados, com protocolo sanitário de desmama completo. Prontos para a recria.', '["https://images.unsplash.com/photo-1661562862223-ff3e853feafb?auto=format&fit=crop&w=1200&q=85"]', 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  ('demo-vendedor', 'publicado', 'Lote de reposição', 'Outros', 'Nelore', 'Fêmeas', 30, 8, '12 a 18 meses', 15, 'Recria', 2300, 'Estância Boa Água', 'Sérgio', 'Campo Grande', 'MS', -20.47, -54.65, 'Pasto', 'Em dia (aftosa e brucelose)', 'Identificação da fazenda', 'A emitir após a negociação', 'Fêmeas jovens para reposição de plantel, em boa condição corporal e com vacinação em dia.', '["https://images.unsplash.com/photo-1608671071793-db93efcf33df?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1554145707-80e42bdaaa4a?auto=format&fit=crop&w=1200&q=85"]', 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days'));

INSERT INTO questions (lot_id, author_id, question, answer, created_at, answered_at)
SELECT id, 'demo-comprador', 'Os animais já foram vacinados contra aftosa?', 'Sim, a vacinação está em dia. O comprovante aparece nos documentos da carga.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days') FROM lots WHERE is_demo = 1 AND name = 'Nelore selecionado';
INSERT INTO questions (lot_id, author_id, question, answer, created_at, answered_at)
SELECT id, 'demo-comprador', 'Qual o prazo para embarque depois da compra?', 'Até 7 dias após a confirmação do pagamento.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days') FROM lots WHERE is_demo = 1 AND name = 'Nelore selecionado';
INSERT INTO questions (lot_id, author_id, question, answer, created_at, answered_at)
SELECT id, 'demo-comprador', 'As fêmeas já foram expostas ao touro?', 'Não. O lote está vazio e pronto para a estação de monta.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days') FROM lots WHERE is_demo = 1 AND name = 'Angus premium';
INSERT INTO questions (lot_id, author_id, question, answer, created_at, answered_at)
SELECT id, 'demo-comprador', 'O lote aceita embarque em carreta de dois andares?', 'Sim, o curral tem embarcadouro para carreta de dois andares.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days') FROM lots WHERE is_demo = 1 AND name = 'Cruza industrial';
